
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: soa_next_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_BACKEND_URL= ${NEXT_PUBLIC_BACKEND_URL}
    depends_on: []
    networks:
      - soa_shared_network

networks:
  soa_shared_network:
    external: true